/*
 * Cresus EVO - timeline.h 
 * 
 * Created by Joachim Naulet <jnaulet@rdinnovation.fr> on 04/06/16
 * Copyright (c) 2016 Joachim Naulet. All rights reserved.
 *
 */

#ifndef TIMELINE_H
#define TIMELINE_H

#include "framework/list.h"
#include "framework/alloc.h"
#include "framework/slist.h"
#include "framework/time_info.h"

/* Automatically generated by script/superclass */
#define __inherits_from_timeline__ struct timeline __parent_timeline__
#define __timeline_is_superclass__ void *__self_timeline__
#define __timeline__(x) (&((x)->__parent_timeline__))
#define __timeline_self__(x) ((struct timeline*)x)->__self_timeline__
#define __timeline_self_init__(x, self) (x)->__self_timeline__ = self

#define __timeline_super__(self, name, input)		    \
  __timeline_self_init__(__timeline__(self), self);	    \
  timeline_init(__timeline__(self), name, input);
#define __timeline_release__(self) timeline_release(__timeline__(self));

#define __timeline_append_entry__(x, entry)	\
  timeline_append_entry(__timeline__(x), entry)

#define TIMELINE_NAME_MAX 256

/* Object is allocatable */
#define timeline_alloc(t, name)                         \
  DEFINE_ALLOC(struct timeline, t, timeline_init, name)
#define timeline_free(t)			\
  DEFINE_FREE(t, timeline_release)

#include "framework/input.h"
#include "framework/indicator.h"
#include "framework/timeline_entry.h"

struct timeline {
  /* "Listable" & "Heritable" */
  __inherits_from_slist__;
  __timeline_is_superclass__;
  /* Internals */
  char name[TIMELINE_NAME_MAX];
  /* Main data */
  list_head_t(struct timeline_entry) list_entry;
  slist_head_t(struct indicator) slist_indicator;
  /* Parser (?) */
  struct timeline_entry *current;
};

int timeline_init(struct timeline *ctx, const char *name);
void timeline_release(struct timeline *ctx);

void timeline_add_indicator(struct timeline *ctx, struct indicator *i);
void timeline_load(struct timeline *ctx, struct input *in);

/* TODO : obsolete ? */
struct timeline_entry *timeline_step(struct timeline *ctx);
int timeline_entry_current(struct timeline *ctx, struct timeline_entry **e);

#endif

